# ======================
# Theme (Catppuccin Mocha)
# ======================
include themes/catppuccin-mocha.conf

# ======================
# Font
# ======================
font_family      JetBrainsMonoNL Nerd Font
font_size        20.0

# ======================
# Appearance
# ======================
window_padding_width  12 8

# Hide window decorations (title bar + buttons)
hide_window_decorations titlebar-only

# Transparent + blurred background
background_opacity      0.75
background_blur         32

# Blank window title
title                   " "
confirm_os_window_close 0


# BEGIN_KITTY_THEME
# Catppuccin-Mocha
include current-theme.conf
# END_KITTY_THEME
